### ISSUE TITLE
service status "504 Gateway Time-out" on secondary when primary is down

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#117]
When primary is down and secondary takes the gridcell control, the services status is not loading when we select 'services' tab.

**Comment by ramaseshan** [comment]
This would work
Refer to #124  for more info.
This basically is a timeout issue. When Primary goes down, for secondary to take complete control, we would about 2-3 minutes. After that, we are really good.

**Comment by ramaseshan** [comment]
Unable to replicate this in gridcellv1.1-rc2. @naveen-fractlio Can you confirm
