### ISSUE TITLE
GDRICell issues

### ISSUE THREAD

**Issue by gattupally** [integralstor/integralstor_gridcell#120]
1) Configuration of the Email alerts fine, but not getting alerts for Volumes, shares creation and Quota modifications, Volumes stop and start, Services stop and start, Secondary node reboot and System errors.

2) After restarting the Gridcell Primary node we have to mandatory restart the Secondary and Slaves. If not Secondary status will be displayed as Failed or Unhealthy.

3) After creating the Volume, we need to Start the Volume. With the current design we need to perform the start operation twice. Suggestion would be Start First and Confirmation Next.

4) In Volumes, Space utilization is displayed in KB, Suggestion would be to display it in GB.

5) Volumes, CIFS shares Quotas configuration takes too much time for processing.

6) So far have created 20 Volumes and the sorting order is not correct. Sorting should be Vol1, Vol2, Vol3 and so on till Vol20. But now it get displayed in the order Vol1, Vol2, Vol10, Vol11...Vol19, Vol2, Vol20...

7) Have configured 20 Volumes so far, have started 19 Volumes so far.  20Volume not getting Started, GUI not responding, need to restart glusterd server every time.

8) Quota settings size not visible under windows OS share properties it is visible total unit size.

9) Local Group creation option is not there.

10) In Memory, Space utilization is displayed in KB, Suggestion would be to display it in MB.

**Comment by fractalram** [comment]
Raju, the bugs listed here have been created separately as individual bugs so can I go ahead and close this one?
