### ISSUE TITLE
Cron need to be updated for log collection mechanism, specific to primary and secondary on first time setup.

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#150]
This "(crontab -l 2>/dev/null; echo "0 6 \* \* \* /usr/bin/python /opt/integralstor/integralstor_gridcell/scripts/python/collect_logs.py > /tmp/collect_logs_alerts >> /tmp/collect_logs_errors") | crontab -" should be added for primary and secondary crons.

**Comment by fractalram** [comment]
This system has been completely revamped so no longer valid..
