### ISSUE TITLE
INSTALL - Change minimum userids for gridcell and uid/gid for integralstor user to 1000

### ISSUE THREAD

**Issue by fractalram** [integralstor/integralstor_gridcell#152]
We need to change the minimum userid for gridcell users also to start with 1000 like we did for unicell. Also need to change the userid and groupid for the integralstor user to 1000 instead of 500

**Comment by naveen-fractlio** [comment]
Changes made on minimum UID/GID for users integralstor is reflected on new install. Verified on release tag https://github.com/integralstor/integralstor_gridcell/releases/tag/g2.0.1.rc1. Hence closing this now.

**Comment by naveen-fractlio** [comment]
Verified against commit ab3bc7f and release tag https://github.com/integralstor/integralstor_gridcell/tree/g2.0.1.rc3
