### ISSUE TITLE
Creating new local user fails on gridcell..

### ISSUE THREAD

**Issue by fractalram** [integralstor/integralstor_gridcell#153]
This is because of issue #152 ..

**Comment by fractalram** [comment]
The error message about the template base should also be fixed now with commit d994fbb

**Comment by naveen-fractlio** [comment]
Able to create new users without any errors. Hence closing this issue now. Tested on release https://github.com/integralstor/integralstor_gridcell/releases/tag/g2.0.1.rc1.

**Comment by naveen-fractlio** [comment]
Verified against commit ab3bc7f and release tag https://github.com/integralstor/integralstor_gridcell/tree/g2.0.1.rc3
