### ISSUE TITLE
Local user authentication for guest users fails on gridcell

### ISSUE THREAD

**Issue by fractalram** [integralstor/integralstor_gridcell#154]

**Comment by fractalram** [comment]
This could be related to #152 as the code changes the permissions of the volumes for uid 1000 but integralstor still points to uid 1000.

Naveen, I have manually changed the uid/gid for the integralstor users to 1000 so please try this again first thing on monday morning to see if it fixes the issue.

**Comment by fractalram** [comment]
Just tested it with the updated UID and it works. Naveen, please mark as fixed once the ks file is updated and tested on a new build.

**Comment by naveen-fractlio** [comment]
Ok Ram, I Updated the ks file for uid/gid changes. And will verify the same on fresh install.

**Comment by naveen-fractlio** [comment]
Local user authentication for guest users works fine. Able to create/modify the files from cifs shares. Hence closing this issue now. Tested on release https://github.com/integralstor/integralstor_gridcell/releases/tag/g2.0.1.rc1.

**Comment by naveen-fractlio** [comment]
Verified against commit ab3bc7f and release tag https://github.com/integralstor/integralstor_gridcell/tree/g2.0.1.rc3
