### ISSUE TITLE
Disk replacement not working..

### ISSUE THREAD

**Issue by fractalram** [integralstor/integralstor_gridcell#155]

**Comment by fractalram** [comment]
Couple of things with this bug : 

1. For gridcell, disk replacement will only work for disks that are being replaced in place. The ability to choose an already inserted but ununsed disk is not there (as we pull in all inserted disks into the pool at install time). What you were trying was that you had created the initial pool with 3 disks, then inserted the fourth and then pulled out a used disk and then tried. This is not supported in gridcell now.

2. The d/b with the new tasks table was not checked it.

**Comment by fractalram** [comment]
Pushed new db schema with commit id d994fbb.

**Comment by naveen-fractlio** [comment]
Disk replacement works fine. And also the scheduled background jobs also runs ok. Tested on release tag https://github.com/integralstor/integralstor_gridcell/releases/tag/g2.0.1.rc1. Hence closing this issue.

**Comment by naveen-fractlio** [comment]
Verified against commit ab3bc7f and release tag https://github.com/integralstor/integralstor_gridcell/tree/g2.0.1.rc3
