### ISSUE TITLE
Unable to access gridcell IntegralView on system Reboot/PowerON

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#156]
Its observed that the uswgi service was not running when system powered ON or Rebooted.

**URL** : "IP/dashboard/"

**UI Path** : "Gridcell IP >> 404 error page"

**Expected Result** : "Able to login and access the gridcell IntegralView."

**Screenshot/s** : 
![gridcell_unable_to_access_integralview](https://cloud.githubusercontent.com/assets/11418556/21764957/cbdb7822-d68b-11e6-97f5-1e3f99223a25.png)

**Comment by fractalram** [comment]
Fixed in commit c89ee5f.

**Comment by naveen-fractlio** [comment]
Its working ok. Tested on release tag https://github.com/integralstor/integralstor_gridcell/releases/tag/g2.0.1.rc1. Hence closing this issue now.

**Comment by naveen-fractlio** [comment]
Verified against commit https://github.com/integralstor/integralstor_gridcell/commit/ab3bc7f00b23872c12e620010caeb453958ca5ea and release tag https://github.com/integralstor/integralstor_gridcell/releases/tag/g2.0.1.rc3
