### ISSUE TITLE
Gridcell information showing 'Not part of storage pool' for first gridcell when we access IntegralView from second.

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#158]
When we access the gridcell IntegralView from second gridcel IP the first gridcell information shows 'Not part of storage pool' in storage pool status.

But When we access IntegrView from first gridcell's IP means its shows all Gridcell information OK.

**URL** : "/view_gridcells/"

**UI PATH** : "Gridcells >> Gridcell Information >> Storage pool status row."

**Expected result** : "Should same gridcell information as shown in first gridcell."

**Screenshot** :
![desktop 1_205](https://cloud.githubusercontent.com/assets/11418556/21850642/986db156-d831-11e6-94ca-dd04da1734aa.png)

**Comment by fractalram** [comment]
Fixed in commit a80f25c

**Comment by naveen-fractlio** [comment]
Its showing correct information when we access it from second/ip gridcell also. Hence closing it now. Verified against commit ab3bc7f and release tag https://github.com/integralstor/integralstor_gridcell/tree/g2.0.1.rc3

![gridcell_info_whn_from_2nd](https://cloud.githubusercontent.com/assets/11418556/21924964/579aa23a-d9a1-11e6-9b29-f33c17f6c444.png)
