### ISSUE TITLE
Error performing audit operation

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#172]
### System information:

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | "CentOS Linux"
Distribution Version    | "6.6"
Linux Kernel                 | "2.6.32-504.el6.x86_64"
Architecture                 | "x86_64"
IntegralSTOR Version                  | "master", "commit id: https://github.com/integralstor/integralstor_gridcell/commit/75aaa10b3b3eab8ff5364d4c04ebb00fbcfe52fe"

### Describe the problem you're observing
1. Not able get audits for most of the UI configurations including user creation, volume creating etc..,

### Describe the expected behaviour
1. Able to get audits for configuration done using views.

### Describe how to reproduce the problem
* Create new user.
* Create new volume.
### Include any warning/errors/backtraces from the system logs:
1.  Create a volume : 
     "Error creating a volume

      Error Details : An error occurred when processing your request : Error performing an audit operation : 'dict' object has no attribute 'META' "

**screenshots**:
1. 
![gridcell_error_adding_node_to_gridcell](https://cloud.githubusercontent.com/assets/11418556/24858903/d52feb7a-1e0b-11e7-9418-8d81bf45d2de.png)
![gridcell_error_creating_local_user](https://cloud.githubusercontent.com/assets/11418556/24858902/d52dadce-1e0b-11e7-8908-30698fa16999.png)

**Comment by naveen-fractlio** [comment]
For this to work need to update the db with audit table and remove attribute META.

**Comment by fractalram** [comment]
Commit 5cea7b7 has the following changes - changed the audit calls to remove the META. Changed the db schema and created a new schema file called integral_view_config.schema. So the install process should now create the db using sqlite3 integral_view_config.db < integral_view_config.schema.

I still have not fixed the audit logs screens and rolling of audit logs. Please dont check them for now but file a bug for those.

**Comment by naveen-fractlio** [comment]
@fractalram 'gridcell_management.py' in views still have ".META" in it, causing audit error.

**Comment by fractalram** [comment]
Fixed with commit aa06103. Also needed a change in the function defn..

**Comment by naveen-fractlio** [comment]
Its working fine tested under commit id https://github.com/integralstor/integralstor_gridcell/commit/aa061036e751d2abce4f1a07a758c5c3fe8e1cf2.
