### ISSUE TITLE
Not able to login to IntegralView with admin user and password

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#173]
### System information:

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | "CentOS Linux"
Distribution Version    | "6.6"
Linux Kernel                 | "2.6.32-504.el6.x86_64"
Architecture                 | "x86_64"
IntegralSTOR Version                  | "master", "commit id: https://github.com/integralstor/integralstor_gridcell/commit/5cea7b746f8ccbd2f7f8ff0c2b117a25294ff03e"

### Describe the problem you're observing
1. Not able to login to IntegralView with the existing admin username and password.

### Describe the expected behaviour
1. Able to login to IntegralView.

### Describe how to reproduce the problem
* On fresh install try login.

**Comment by fractalram** [comment]
Shd be fixed with commit 5dfc440. However, like integralstor, we will now use admin[1..4] as the username

**Comment by naveen-fractlio** [comment]
Its working fine tested under the commit id https://github.com/integralstor/integralstor_gridcell/commit/5dfc440df6f16a08bf6426c1b02a73bcf8d60f30. Hence closing it now.
