### ISSUE TITLE
'login_required' missing in most of the views results in direct access into IntegralView using URLs without username and password.

### ISSUE THREAD

**Issue by naveen-fractlio** [integralstor/integralstor_gridcell#176]
### System information:

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | "CentOS Linux"
Distribution Version    | "6.6 (Core)"
Linux Kernel                 | "2.6.32-504.el6.x86_64"
Architecture                 | "x86_64"
Integralstor Version                  | "master" commit id : "https://github.com/integralstor/integralstor_gridcell/commit/5dfc440df6f16a08bf6426c1b02a73bcf8d60f30"

### Describe the problem you're observing
1. On using urls(like IP/view_gridcells,IP/dashboard etc.,) can give access to the gridcell without authentication. 

### Describe the expected behaviour
* Should asks for username and password for all the views.

### Describe how to reproduce the problem
* On fresh install after configuring gridcell try accessing gridcell with ursl like above.

**Comment by fractalram** [comment]
Fixed with commit 9d6e38d. The is_authenticated is supposed to be a function call and not a True/False flag.

**Comment by naveen-fractlio** [comment]
Tested and verified under commit id : https://github.com/integralstor/integralstor_gridcell/commit/aa061036e751d2abce4f1a07a758c5c3fe8e1cf2. Hence closing this issue.
