### ISSUE TITLE
Error creating samba share for guest user

### ISSUE THREAD

**Issue by naveenmh** [integralstor/integralstor_gridcell#178]
### System information:

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | "CentOS Linux"
Distribution Version    | "6.6 (Core)"
Linux Kernel                 | "2.6.32-504.el6.x86_64"
Architecture                 | "x86_64"
Integralstor Version                  | "master" commit id : "https://github.com/integralstor/integralstor_gridcell/commit/aa061036e751d2abce4f1a07a758c5c3fe8e1cf2"

### Describe the problem you're observing
1. Error message on while creating samba share but actually created the share. 

### Describe the expected behaviour
* Should be able to create the share without errors.

### Describe how to reproduce the problem
* On fresh install after configuring gridcell try creating share.

### Error page/screens
![gridcell_error_creating_shares_for_guest_user](https://cloud.githubusercontent.com/assets/11418556/25275343/692aa5f0-26b2-11e7-9f79-24d4112349f3.png)

**Comment by naveen-fractlio** [comment]
cifs.py in integralstor_utils, cmd_list = [] is initialized inside the if condition. Need to put it out, will fix this issue.

**Comment by six-k** [comment]
https://github.com/integralstor/integralstor_utils/pull/26
